# Generated by Django 4.1.2 on 2022-10-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course_ide',
            new_name='course_id',
        ),
    ]
