# Generated by Django 4.1.2 on 2022-10-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_course_ide_student_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='do', max_length=100),
        ),
    ]
