# Generated by Django 4.1.2 on 2022-11-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_studentresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='continuousevaluation_mark',
            new_name='assignment_mark',
        ),
        migrations.RenameField(
            model_name='studentresult',
            old_name='see_mark',
            new_name='exam_mark',
        ),
    ]
