# Generated by Django 4.1.2 on 2022-12-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_fees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendance_data',
            new_name='attendance_date',
        ),
    ]
