# Generated by Django 4.1.2 on 2022-12-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_attendance_data_attendance_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_report',
            old_name='atteendance_id',
            new_name='attendance_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='session_year_id',
        ),
    ]
