# Generated by Django 4.1.2 on 2022-12-27 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_atteendance_id_attendance_report_attendance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session_year_id',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.DO_NOTHING, to='app.session_year'),
        ),
    ]
