# Generated by Django 4.1.2 on 2022-12-27 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_attendance_session_year_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='session_year_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.session_year'),
        ),
    ]
